from setuptools import setup, find_packages

setup(
    name="banditpylib",
    version="0.1.0",
    author="Chester Holtz, Chao Tao",
    author_email="chholtz@eng.ucsd.edu, sdutaochao@gmail.com",
    description="A lightweight python library for bandit algorithms",
    url="https://github.com/Alanthink/banditpylib",
    packages=[package for package in find_packages()
              if package.startswith('banditpylib')],
    install_requires=[
        'absl-py',
        'attrs',
        'Click',
        'cvxpy',
        'cycler',
        'dill',
        'ecos',
        'future',
        'glog',
        'importlib-metadata',
        'kiwisolver',
        'matplotlib',
        'more-itertools',
        'multiprocess',
        'numpy',
        'osqp',
        'packaging',
        'pandas',
        'pluggy',
        'py',
        'pyparsing',
        'pytest',
        'python-dateutil',
        'python-gflags',
        'pytz',
        'PyYAML',
        'scipy',
        'scs',
        'seaborn',
        'six',
        'tabulate',
        'wcwidth',
        'zipp'
    ]
)
