# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='banditpylib',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\x12\x0b\x62\x61nditpylib\"\"\n\x11SequentialContext\x12\r\n\x05value\x18\x01 \x03(\x02\"\x17\n\x06Vector\x12\r\n\x05value\x18\x01 \x03(\x02\"9\n\x11VectorizedContext\x12$\n\x07vectors\x18\x01 \x03(\x0b\x32\x13.banditpylib.Vector\"\x95\x01\n\x07\x43ontext\x12<\n\x12sequential_context\x18\x01 \x01(\x0b\x32\x1e.banditpylib.SequentialContextH\x00\x12<\n\x12vectorized_context\x18\x02 \x01(\x0b\x32\x1e.banditpylib.VectorizedContextH\x00\x42\x0e\n\x0c\x63ontext_type\"W\n\x03\x41rm\x12\x0c\n\x02id\x18\x01 \x01(\x05H\x00\x12#\n\x03set\x18\x02 \x01(\x0b\x32\x14.banditpylib.Arm.SetH\x00\x1a\x11\n\x03Set\x12\n\n\x02id\x18\x01 \x03(\x05\x42\n\n\x08\x61rm_type\"7\n\x07\x41rmPull\x12\x1d\n\x03\x61rm\x18\x01 \x01(\x0b\x32\x10.banditpylib.Arm\x12\r\n\x05times\x18\x02 \x01(\x05\"\x96\x01\n\x07\x41\x63tions\x12\'\n\tarm_pulls\x18\x01 \x03(\x0b\x32\x14.banditpylib.ArmPull\x12-\n\x05state\x18\x02 \x01(\x0e\x32\x1e.banditpylib.Actions.StateType\"3\n\tStateType\x12\x12\n\x0e\x44\x45\x46\x41ULT_NORMAL\x10\x00\x12\x08\n\x04WAIT\x10\x01\x12\x08\n\x04STOP\x10\x02\"Y\n\x0b\x41rmFeedback\x12\x1d\n\x03\x61rm\x18\x01 \x01(\x0b\x32\x10.banditpylib.Arm\x12\x0f\n\x07rewards\x18\x02 \x03(\x02\x12\x1a\n\x12\x63ustomer_feedbacks\x18\x03 \x03(\x05\";\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12/\n\rarm_feedbacks\x18\x01 \x03(\x0b\x32\x18.banditpylib.ArmFeedback\"N\n\x06Result\x12\x0e\n\x06rounds\x18\x01 \x01(\x05\x12\x15\n\rtotal_actions\x18\x02 \x01(\x05\x12\x0e\n\x06regret\x18\x03 \x01(\x02\x12\r\n\x05other\x18\x04 \x01(\x02\"N\n\x05Trial\x12\x0e\n\x06\x62\x61ndit\x18\x01 \x01(\t\x12\x0f\n\x07learner\x18\x02 \x01(\t\x12$\n\x07results\x18\x03 \x03(\x0b\x32\x13.banditpylib.Resultb\x06proto3'
)



_ACTIONS_STATETYPE = _descriptor.EnumDescriptor(
  name='StateType',
  full_name='banditpylib.Actions.StateType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT_NORMAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WAIT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=545,
  serialized_end=596,
)
_sym_db.RegisterEnumDescriptor(_ACTIONS_STATETYPE)


_SEQUENTIALCONTEXT = _descriptor.Descriptor(
  name='SequentialContext',
  full_name='banditpylib.SequentialContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='banditpylib.SequentialContext.value', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=61,
)


_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='banditpylib.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='banditpylib.Vector.value', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=86,
)


_VECTORIZEDCONTEXT = _descriptor.Descriptor(
  name='VectorizedContext',
  full_name='banditpylib.VectorizedContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vectors', full_name='banditpylib.VectorizedContext.vectors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=145,
)


_CONTEXT = _descriptor.Descriptor(
  name='Context',
  full_name='banditpylib.Context',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequential_context', full_name='banditpylib.Context.sequential_context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vectorized_context', full_name='banditpylib.Context.vectorized_context', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='context_type', full_name='banditpylib.Context.context_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=148,
  serialized_end=297,
)


_ARM_SET = _descriptor.Descriptor(
  name='Set',
  full_name='banditpylib.Arm.Set',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='banditpylib.Arm.Set.id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=374,
)

_ARM = _descriptor.Descriptor(
  name='Arm',
  full_name='banditpylib.Arm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='banditpylib.Arm.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set', full_name='banditpylib.Arm.set', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ARM_SET, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='arm_type', full_name='banditpylib.Arm.arm_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=299,
  serialized_end=386,
)


_ARMPULL = _descriptor.Descriptor(
  name='ArmPull',
  full_name='banditpylib.ArmPull',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='arm', full_name='banditpylib.ArmPull.arm', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='times', full_name='banditpylib.ArmPull.times', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=443,
)


_ACTIONS = _descriptor.Descriptor(
  name='Actions',
  full_name='banditpylib.Actions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='arm_pulls', full_name='banditpylib.Actions.arm_pulls', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='banditpylib.Actions.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACTIONS_STATETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=596,
)


_ARMFEEDBACK = _descriptor.Descriptor(
  name='ArmFeedback',
  full_name='banditpylib.ArmFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='arm', full_name='banditpylib.ArmFeedback.arm', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rewards', full_name='banditpylib.ArmFeedback.rewards', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='customer_feedbacks', full_name='banditpylib.ArmFeedback.customer_feedbacks', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=687,
)


_FEEDBACK = _descriptor.Descriptor(
  name='Feedback',
  full_name='banditpylib.Feedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='arm_feedbacks', full_name='banditpylib.Feedback.arm_feedbacks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=689,
  serialized_end=748,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='banditpylib.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rounds', full_name='banditpylib.Result.rounds', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_actions', full_name='banditpylib.Result.total_actions', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regret', full_name='banditpylib.Result.regret', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='other', full_name='banditpylib.Result.other', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=750,
  serialized_end=828,
)


_TRIAL = _descriptor.Descriptor(
  name='Trial',
  full_name='banditpylib.Trial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bandit', full_name='banditpylib.Trial.bandit', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='learner', full_name='banditpylib.Trial.learner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='results', full_name='banditpylib.Trial.results', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=830,
  serialized_end=908,
)

_VECTORIZEDCONTEXT.fields_by_name['vectors'].message_type = _VECTOR
_CONTEXT.fields_by_name['sequential_context'].message_type = _SEQUENTIALCONTEXT
_CONTEXT.fields_by_name['vectorized_context'].message_type = _VECTORIZEDCONTEXT
_CONTEXT.oneofs_by_name['context_type'].fields.append(
  _CONTEXT.fields_by_name['sequential_context'])
_CONTEXT.fields_by_name['sequential_context'].containing_oneof = _CONTEXT.oneofs_by_name['context_type']
_CONTEXT.oneofs_by_name['context_type'].fields.append(
  _CONTEXT.fields_by_name['vectorized_context'])
_CONTEXT.fields_by_name['vectorized_context'].containing_oneof = _CONTEXT.oneofs_by_name['context_type']
_ARM_SET.containing_type = _ARM
_ARM.fields_by_name['set'].message_type = _ARM_SET
_ARM.oneofs_by_name['arm_type'].fields.append(
  _ARM.fields_by_name['id'])
_ARM.fields_by_name['id'].containing_oneof = _ARM.oneofs_by_name['arm_type']
_ARM.oneofs_by_name['arm_type'].fields.append(
  _ARM.fields_by_name['set'])
_ARM.fields_by_name['set'].containing_oneof = _ARM.oneofs_by_name['arm_type']
_ARMPULL.fields_by_name['arm'].message_type = _ARM
_ACTIONS.fields_by_name['arm_pulls'].message_type = _ARMPULL
_ACTIONS.fields_by_name['state'].enum_type = _ACTIONS_STATETYPE
_ACTIONS_STATETYPE.containing_type = _ACTIONS
_ARMFEEDBACK.fields_by_name['arm'].message_type = _ARM
_FEEDBACK.fields_by_name['arm_feedbacks'].message_type = _ARMFEEDBACK
_TRIAL.fields_by_name['results'].message_type = _RESULT
DESCRIPTOR.message_types_by_name['SequentialContext'] = _SEQUENTIALCONTEXT
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['VectorizedContext'] = _VECTORIZEDCONTEXT
DESCRIPTOR.message_types_by_name['Context'] = _CONTEXT
DESCRIPTOR.message_types_by_name['Arm'] = _ARM
DESCRIPTOR.message_types_by_name['ArmPull'] = _ARMPULL
DESCRIPTOR.message_types_by_name['Actions'] = _ACTIONS
DESCRIPTOR.message_types_by_name['ArmFeedback'] = _ARMFEEDBACK
DESCRIPTOR.message_types_by_name['Feedback'] = _FEEDBACK
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Trial'] = _TRIAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SequentialContext = _reflection.GeneratedProtocolMessageType('SequentialContext', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENTIALCONTEXT,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:banditpylib.SequentialContext)
  })
_sym_db.RegisterMessage(SequentialContext)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:banditpylib.Vector)
  })
_sym_db.RegisterMessage(Vector)

VectorizedContext = _reflection.GeneratedProtocolMessageType('VectorizedContext', (_message.Message,), {
  'DESCRIPTOR' : _VECTORIZEDCONTEXT,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:banditpylib.VectorizedContext)
  })
_sym_db.RegisterMessage(VectorizedContext)

Context = _reflection.GeneratedProtocolMessageType('Context', (_message.Message,), {
  'DESCRIPTOR' : _CONTEXT,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:banditpylib.Context)
  })
_sym_db.RegisterMessage(Context)

Arm = _reflection.GeneratedProtocolMessageType('Arm', (_message.Message,), {

  'Set' : _reflection.GeneratedProtocolMessageType('Set', (_message.Message,), {
    'DESCRIPTOR' : _ARM_SET,
    '__module__' : 'data_pb2'
    # @@protoc_insertion_point(class_scope:banditpylib.Arm.Set)
    })
  ,
  'DESCRIPTOR' : _ARM,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:banditpylib.Arm)
  })
_sym_db.RegisterMessage(Arm)
_sym_db.RegisterMessage(Arm.Set)

ArmPull = _reflection.GeneratedProtocolMessageType('ArmPull', (_message.Message,), {
  'DESCRIPTOR' : _ARMPULL,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:banditpylib.ArmPull)
  })
_sym_db.RegisterMessage(ArmPull)

Actions = _reflection.GeneratedProtocolMessageType('Actions', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONS,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:banditpylib.Actions)
  })
_sym_db.RegisterMessage(Actions)

ArmFeedback = _reflection.GeneratedProtocolMessageType('ArmFeedback', (_message.Message,), {
  'DESCRIPTOR' : _ARMFEEDBACK,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:banditpylib.ArmFeedback)
  })
_sym_db.RegisterMessage(ArmFeedback)

Feedback = _reflection.GeneratedProtocolMessageType('Feedback', (_message.Message,), {
  'DESCRIPTOR' : _FEEDBACK,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:banditpylib.Feedback)
  })
_sym_db.RegisterMessage(Feedback)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:banditpylib.Result)
  })
_sym_db.RegisterMessage(Result)

Trial = _reflection.GeneratedProtocolMessageType('Trial', (_message.Message,), {
  'DESCRIPTOR' : _TRIAL,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:banditpylib.Trial)
  })
_sym_db.RegisterMessage(Trial)


# @@protoc_insertion_point(module_scope)
