name: Style Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Lint with pylint
      run: |
        pip install pylint
        git diff --name-only "$GITHUB_BASE_REF..$GITHUB_SHA" | xargs pylint **/*.py
